version: '3.4'

services:
    db:
        image: postgres:16.0-alpine3.18
        container_name: fsc-db
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        expose:
            - "5432"
        volumes:
            - ./storage/db:/var/lib/postgresql/data

    api:
        build:
            context: ./src/api
            dockerfile: Dockerfile
        container_name: fsc-api
        restart: unless-stopped
        command: /bin/sh -c "uvicorn main:start_app --host 0.0.0.0 --port 8000 --factory"
        environment:
            - DB_LINK=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
            - ALEMBIC_LINK=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
        ports:
            - "8000:8000"
        volumes:
            - ./src/api:/app
        depends_on:
            - "db"

    dashboard:
        build:
            context: ./src/dashboard
            dockerfile: Dockerfile
            target: development
        container_name: fsc-dashboard
        restart: unless-stopped
        command: /bin/sh -c "yarn dev"
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./src/dashboard:/app
        depends_on:
            - "api"
